export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
export const DIALOG_AREA_TREE_OPEN = "DIALOG_AREA_TREE_OPEN";
export const DIALOG_AREA_TREE_CLOSE = "DIALOG_AREA_TREE_CLOSE";